#!/bin/bash

# Simple AI Project Initializer
# Usage: Run this inside your project directory

echo "🚀 AI Project Initializer"
echo "========================="
echo ""

# Check if we're in a directory
if [ ! -d "$(pwd)" ]; then
    echo "❌ Error: Not in a valid directory"
    exit 1
fi

PROJECT_DIR=$(pwd)
PROJECT_NAME=$(basename "$PROJECT_DIR")

echo "📁 Current directory: $PROJECT_DIR"
echo "📦 Project name: $PROJECT_NAME"
echo ""

# Ask for project description
read -p "📝 What do you want to build? (e.g., 'fitness tracker app'): " PROJECT_DESC

if [ -z "$PROJECT_DESC" ]; then
    echo "❌ Description required"
    exit 1
fi

echo ""
echo "🤖 AI is analyzing your requirements..."
echo ""

# Choose tech stack
echo "🔧 Choose your tech stack:"
echo "1) React + Node.js (Full-stack web app)"
echo "2) React only (Frontend only)"
echo "3) Next.js (Full-stack with SSR)"
echo "4) React Native (Mobile app)"
echo ""
read -p "Select (1-4): " STACK_CHOICE

case $STACK_CHOICE in
    1)
        STACK="react-node"
        echo "✅ Selected: React + Node.js"
        ;;
    2)
        STACK="react"
        echo "✅ Selected: React"
        ;;
    3)
        STACK="nextjs"
        echo "✅ Selected: Next.js"
        ;;
    4)
        STACK="react-native"
        echo "✅ Selected: React Native"
        ;;
    *)
        STACK="react-node"
        echo "✅ Default: React + Node.js"
        ;;
esac

echo ""
echo "🏗️  Creating project structure..."
echo ""

# Create based on stack
if [ "$STACK" = "react-node" ]; then
    # Create React + Node.js project
    echo "📦 Creating React frontend..."
    npm create vite@latest frontend -- --template react-ts
    
    echo ""
    echo "📦 Creating Node.js backend..."
    mkdir -p backend/src
    
    # Create backend files
    cat > backend/package.json << 'EOF'
{
  "name": "backend",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "tsx watch src/index.ts",
    "build": "tsc"
  },
  "dependencies": {
    "express": "^4.18.0",
    "cors": "^2.8.5",
    "dotenv": "^16.0.0"
  },
  "devDependencies": {
    "@types/express": "^4.17.0",
    "@types/cors": "^2.8.0",
    "typescript": "^5.3.0",
    "tsx": "^4.0.0"
  }
}
EOF

    cat > backend/src/index.ts << 'EOF'
import express from 'express';
import cors from 'cors';

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', message: 'Server is running' });
});

app.listen(PORT, () => {
  console.log(`🚀 Server running on http://localhost:${PORT}`);
});
EOF

    cat > backend/tsconfig.json << 'EOF'
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "strict": true,
    "skipLibCheck": true,
    "outDir": "./dist"
  },
  "include": ["src/**/*"]
}
EOF

elif [ "$STACK" = "react" ]; then
    # React only
    echo "📦 Creating React app..."
    npm create vite@latest . -- --template react-ts

elif [ "$STACK" = "nextjs" ]; then
    # Next.js
    echo "📦 Creating Next.js app..."
    npx create-next-app@latest . --typescript --tailwind --app --no-src-dir

elif [ "$STACK" = "react-native" ]; then
    # React Native
    echo "📦 Creating React Native app..."
    npx create-expo-app . --template blank-typescript
fi

echo ""
echo "✅ Project structure created!"
echo ""
echo "📝 Creating README..."

# Create README
cat > README.md << EOF
# $PROJECT_NAME

$PROJECT_DESC

## Tech Stack

- Stack: $STACK

## Getting Started

EOF

if [ "$STACK" = "react-node" ]; then
    cat >> README.md << 'EOF'
### Frontend
```bash
cd frontend
npm install
npm run dev
```

### Backend
```bash
cd backend
npm install
npm run dev
```
EOF
else
    cat >> README.md << 'EOF'
```bash
npm install
npm run dev
```
EOF
fi

cat >> README.md << 'EOF'

## Generated by AI

This project was automatically initialized using AI-driven setup.
EOF

echo "✅ README created"
echo ""
echo "🎉 Project initialized successfully!"
echo ""
echo "📋 Next steps:"

if [ "$STACK" = "react-node" ]; then
    echo "   cd frontend && npm install && npm run dev"
    echo "   cd backend && npm install && npm run dev"
else
    echo "   npm install"
    echo "   npm run dev"
fi

echo ""
echo "💡 Tip: Open this project in VS Code:"
echo "   code ."
echo ""
